# Generated by Django 4.1.3 on 2022-11-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_profile_location_skill"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="profiles/blank.png",
                null=True,
                upload_to="profiles/",
            ),
        ),
    ]
