# Generated by Django 4.1.3 on 2022-11-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_profile_bio_profile_short_intro_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="profiles/blankdefault.jpg",
                null=True,
                upload_to="profiles/",
            ),
        ),
    ]
