# Generated by Django 4.1.3 on 2022-12-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profiles/"),
        ),
    ]
