# Generated by Django 4.1.3 on 2022-12-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_alter_profile_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="profile/default.png",
                null=True,
                upload_to="profiles/",
            ),
        ),
    ]
