# Generated by Django 4.1.3 on 2022-11-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_project_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="featured_image",
            field=models.ImageField(
                blank=True, default="blank.png", null=True, upload_to=""
            ),
        ),
    ]
